language: go

sudo: false

branches:
  except:
    # skip tags build, we are building branch and master that is enough for
    # consistenty check and release. Let's use Travis CI resources optimally
    # for aah framework.
    - /^v[0-9]\.[0-9]/

go:
  - 1.11.x
  - tip

go_import_path: github.com/go-aah/forge

script:
  - bash <(curl -s https://aahframework.org/go-test)
  - go test -bench . -benchmem

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip
